#!/bin/bash
set -e

# Stop and disable service before removal
if [ -d /run/systemd/system ]; then
    systemctl stop vsTaskViewer.service || true
    systemctl disable vsTaskViewer.service || true
fi

# DEBHELPER#
exit 0

